name: PR Updates

on:
  pull_request:
    types: [opened, reopened]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    name: Trigger Telegram notifier workflow
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          event-type: pr-opened
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "title": "${{ github.event.pull_request.title }}", "creator": "${{ github.actor }}"}'
